"""Update Activity model: rename host_id to host_username and add description

Revision ID: dd2a229ed49b
Revises: 
Create Date: 2024-09-28 12:03:13.960850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2a229ed49b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('host_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('activities_host_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['host_id'], ['username'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activities_host_id_fkey', 'users', ['host_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('host_id',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
