"""update activity in Users

Revision ID: f221b3feb550
Revises: dd2a229ed49b
Create Date: 2024-09-28 19:06:53.581379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f221b3feb550'
down_revision = 'dd2a229ed49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_activity_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('participant_activity_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'activities', ['participant_activity_id'], ['id'])
        batch_op.create_foreign_key(None, 'activities', ['host_activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('participant_activity_id')
        batch_op.drop_column('host_activity_id')

    # ### end Alembic commands ###
